<Project>
    <PropertyGroup>
        <!-- opt-in / feature flags -->
        <GenerateManagedManifest Condition="'$(GenerateManagedManifest)' == ''">false</GenerateManagedManifest>
        <ContentManager Condition="'$(ContentManager)' == ''">false</ContentManager>

        <!-- stable roots -->
        <SmapiManifestSdkRoot Condition="'$(SmapiManifestSdkRoot)' == ''">$(MSBuildThisFileDirectory)</SmapiManifestSdkRoot>
        <ManifestImportsRoot Condition="'$(ManifestImportsRoot)' == ''">$(SmapiManifestSdkRoot)imports\</ManifestImportsRoot>

        <!-- stable static defaults -->
        <ManifestAuthor Condition="'$(ManifestAuthor)' == ''">$(ManifestVar_Author)</ManifestAuthor>

        <!-- optional behavior switches -->
        <ManifestEmitDebugMessages Condition="'$(ManifestEmitDebugMessages)' == ''">false</ManifestEmitDebugMessages>
    </PropertyGroup>
</Project>