<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\Common\StringUtils\StringUtils.shared.props" />
  <Import Project="..\..\Common\StringUtils\StringUtils.shared.projitems" />

  <PropertyGroup>
    <EnableHarmony>true</EnableHarmony>
    <ModFolderName>$(ModFamilyPrefix) Metal Casting</ModFolderName>

    <Version>1.0.0</Version> 
    <Description>Casting mechanics and gameplay that consume the metals content manager.</Description>

    <GenerateManagedManifest>true</GenerateManagedManifest>
    <ManifestKind>SmapiMod</ManifestKind>

    <ManifestName>It's Stardew Metal Casting</ManifestName>
    <ManifestUniqueId>$(PROJECTVARS_MODS_METALSCASTING)</ManifestUniqueId>
    <ManifestAuthor>$(PROJECTVARS_AUTHOR_NAME)</ManifestAuthor>

    <ManifestIncludeSmapiDependency>false</ManifestIncludeSmapiDependency>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Common\ContentManager\ContentManager.csproj" />
    <Folder Include="Framework\State\" />
  </ItemGroup>
</Project>
