<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <EnableHarmony>true</EnableHarmony>
    <Version>0.5.0</Version>
    <ModFolderName>$(ModFamilyPrefix) Metal Casting</ModFolderName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Pathoschild.Stardew.ModBuildConfig" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\StringUtils\StringUtils.csproj" />
    <ProjectReference Include="..\..\Content-Managers\MetalsContentManager\MetalsContentManager.csproj" />
  </ItemGroup>
</Project>