<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="StringUtils.shared.props" />
  <Import Project="StringUtils.shared.projitems" />

  <PropertyGroup>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <EnableGameDebugging>false</EnableGameDebugging>
    <EnableModDeploy>false</EnableModDeploy>
    <EnableModZip>false</EnableModZip>
    <RootNamespace>Common</RootNamespace>
  </PropertyGroup>
</Project>
