<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>

        <Version>1.0.0</Version>
        <Description>Central manager for metals-related shared assets and APIs.</Description>

        <GenerateManagedManifest>true</GenerateManagedManifest>
        <ManifestKind>SmapiMod</ManifestKind>

        <ManifestName>Metals Content Manager</ManifestName>
        <ManifestUniqueId>$(PROJECTVARS_CONTENT_MANAGERS_METALS)</ManifestUniqueId>
        <ManifestAuthor>$(PROJECTVARS_AUTHOR_NAME)</ManifestAuthor>

        <!-- purely organizational for now -->
        <ContentManager>true</ContentManager>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Pathoschild.Stardew.ModBuildConfig" />
        <ProjectReference Include="..\..\Common\UniqueIds\UniqueIds.csproj" />
    </ItemGroup>
</Project>
